### ISSUE TITLE
Training Details for Reproduction

### ISSUE THREAD

**Issue by Ming-er** [Aria-K-Alethia/BigCodec#10]
Sorry to bother you. I find that in the github config, the total training steps are set as 120k, while the paper claims that the number is 600k. Will it significantly influence the performance? Do I need to train for 600k steps to fully reproduce the results in the paper? Are there any other config settings in the repository different from the paper? Thanks~

**Comment by Aria-K-Alethia** [comment]
Hi,

First, in the config file the training steps is **1200k**, not 120k.
Second, the 600k in the paper means each of the generator and discriminator takes 600k, so nothing different from the code.

**Comment by Ming-er** [comment]
OK, I get it. Sorry for my carelessness.
