### ISSUE TITLE
Release of training code?

### ISSUE THREAD

**Issue by TechInterMezzo** [Aria-K-Alethia/BigCodec#4]
The generalization ability of BigCodec is amazing.
Will you also release training code for this model?

**Comment by Aria-K-Alethia** [comment]
Hi,

Thank you for being interested in our work.

I'm considering to release the training code in the future (but not now).
BTW, could you tell me why do you need the training code?

**Comment by TechInterMezzo** [comment]
I would like to experiment with it and see if and how finetuning is possible. Maybe as a part of a TTS model.

**Comment by Aria-K-Alethia** [comment]
Got it.

I will prepare for it so keep watching  the repo.
Idk what kind of TTS you're going to train, but in case of a quick idea verification or an English TTS, the released ckpt should be enough.

**Comment by flowspeech** [comment]
When will  open source the training code? I used the Wavetokenizer project to modify and reproduce the model, but the generator never converged. The new training always generates empty audio

**Comment by Aria-K-Alethia** [comment]
Hi,

I've updated the training code.
Please find details in `README`.

**Comment by TechInterMezzo** [comment]
That's great. Thank you!
