### ISSUE TITLE
a quetion about scaling up the model size

### ISSUE THREAD

**Issue by VJJJJJJ1** [Aria-K-Alethia/BigCodec#9]
hi, thank you for your great work.
Do you increase the model parameters simply by increasing the number of conv layers while keeping the sample rate constant, thereby improving performance? Have you ever tried to increase N to 6, 7 or more?

**Comment by Aria-K-Alethia** [comment]
Hi,

Yes, we increase parameters while keeping the sample rate constant to improve performance.
I haven't tried larger N, but you are welcomed to try it.
